const {ctx,rows,uuid,props,sheets,setEmail}=require('./server.cjs');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const runtime=process.env.SD_NODE_MODULES||'C:/Users/ULTRA/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
const {chromium}=require(path.join(runtime,'playwright'));
const root=path.join(__dirname,'..');
const {renderHtml}=require('../tools/project.cjs');
(async()=>{
  const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');res.end(renderHtml('Index.html',[],ctx.getClientConfig_()));});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  let browser;const failures=[],rpc=[];let activityGate=null,failActivity=false,failProfile=false;
  try {
    browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
    const page=await browser.newPage({viewport:{width:1280,height:900}});
    page.on('pageerror',e=>{failures.push(e.message);console.error('PAGE:',e.stack);});
    page.on('console',m=>{if(m.type()==='error')console.error('BROWSER:',m.text());});
    await page.exposeFunction('__server',async(name,args)=>{
      rpc.push(name);
      if(name==='runWithProfile'&&failProfile)throw new Error('Profile loading failed');
      if(name==='getCommitmentActivity'&&activityGate) await activityGate;
      if(name==='getCommitmentActivity'&&failActivity) throw new Error('Simulated activity failure');
      if(typeof ctx[name]!=='function'||name.endsWith('_')) throw new Error('Invalid RPC');
      try {return JSON.parse(JSON.stringify(ctx[name](...args)));} catch(e){console.error('RPC:',name,e.message);throw e;}
    });
    await page.addInitScript(()=>{
      function runner(success,failure){return new Proxy({}, {get(_,name){if(name==='withSuccessHandler')return fn=>runner(fn,failure);if(name==='withFailureHandler')return fn=>runner(success,fn);return(...args)=>window.__server(name,args).then(success||(()=>{})).catch(e=>(failure||(()=>{}))({message:e.message}));}});}
      window.google={script:{run:runner()}};
    });
    const boardTask=ctx.createCommitment({titulo:'Kanban browser task',tipo_id:'T',owner_id:'B',aprobador_id:'C',fecha_objetivo:'2026-10-10',request_id:uuid(850)});
    await page.goto(`http://127.0.0.1:${server.address().port}`);
    await page.waitForFunction(()=>document.querySelector('#user-name').textContent==='Admin');
    await page.locator('[data-view="kanban"]').click();
    await page.locator(`[data-board-move="${boardTask.id}"]`).selectOption('EN_CURSO');
    await page.waitForFunction(id=>document.querySelector(`[data-column="EN_CURSO"] [data-card="${id}"]`),boardTask.id);
    await page.locator(`[data-card="${boardTask.id}"]`).dragTo(page.locator('[data-column="BLOQUEADO"]'));
    await page.waitForFunction(id=>document.querySelector(`[data-column="BLOQUEADO"] [data-card="${id}"]`),boardTask.id);
    await page.locator(`[data-card="${boardTask.id}"] [data-action="board-detail"]`).click();
    await page.locator('[data-action="checklist-add"]').click();
    await page.locator('#checklist-items input[type=text]').fill('Preparar evidencia <segura>');
    await page.locator('#checklist-items input[type=checkbox]').check();
    await page.locator('#update-form [name="descripcion"]').fill('Checklist must preserve this draft');
    const checklistVersion=await page.locator('#checklist-form').getAttribute('data-version');
    await page.locator('#checklist-form button[type=submit]').click();
    await page.waitForFunction(version=>document.querySelector('#checklist-form').dataset.version!==version,checklistVersion);
    assert.equal(await page.locator('#update-form [name="descripcion"]').inputValue(),'Checklist must preserve this draft');
    assert.equal(JSON.parse(rows('COMPROMISOS').find(c=>c.compromiso_id===boardTask.id).checklist_json)[0].done,true);
    await page.locator('#detail-dialog [data-action="close-dialog"]').click();
    await page.locator(`[data-card="${boardTask.id}"] [data-action="board-detail"]`).click();
    assert.equal(await page.locator('#checklist-items input[type=text]').inputValue(),'Preparar evidencia <segura>');
    assert.ok(await page.locator('#checklist-items input[type=checkbox]').isChecked());
    await page.locator('#detail-dialog [data-action="close-dialog"]').click();
    await page.locator(`[data-board-move="${boardTask.id}"]`).selectOption('EN_APROBACION');
    await page.waitForFunction(()=>document.querySelector('#evidence-dialog').open);
    assert.equal(rows('COMPROMISOS').find(c=>c.compromiso_id===boardTask.id).estado,'BLOQUEADO');
    await page.locator('#evidence-dialog [data-action="close-dialog"]').first().click();
    await page.locator('#board-search').fill('No matching title');
    assert.equal(await page.locator('[data-card]').count(),0);
    await page.locator('#board-search').fill('');
    await page.screenshot({path:path.join(root,'tests/kanban-preview.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),'Mobile Kanban fits');
    await page.setViewportSize({width:1280,height:900});
    await page.locator('[data-view="admin"]').click();await page.locator('#admin-new').click();
    await page.locator('#feature-form [name="nombre"]').fill('Browser User');
    await page.locator('#feature-form [name="correo_corporativo"]').fill('browser@example.com');
    await page.locator('#feature-save').click();await page.waitForFunction(()=>!document.querySelector('#feature-dialog').open);
    const browserUser=rows('USUARIOS').find(u=>u.correo_corporativo==='browser@example.com');assert.ok(browserUser);
    await page.locator('#admin-section').selectOption('projects');await page.locator('#admin-new').click();
    await page.locator('#feature-form [name="nombre"]').fill('Browser Project');await page.locator('#feature-save').click();await page.waitForFunction(()=>!document.querySelector('#feature-dialog').open);
    assert.ok(rows('PROYECTOS').find(p=>p.nombre==='Browser Project'));
    await page.locator('[data-view="recurrentes"]').click();await page.locator('[data-action="new-recurrence"]').click();
    await page.locator('#feature-form [name="nombre"]').fill('Browser Recurrence');await page.locator('#feature-form [name="tipo_id"]').selectOption('N');await page.locator('#feature-form [name="owner_id"]').selectOption('B');
    await page.locator('#feature-form [name="fecha_inicio"]').fill('2026-10-03');await page.locator('#feature-form [name="proxima_generacion"]').fill('2026-10-03');
    await page.locator('#feature-save').click();await page.waitForFunction(()=>!document.querySelector('#feature-dialog').open);assert.ok(rows('RECURRENCIAS').find(r=>r.nombre==='Browser Recurrence'));
    await page.locator('[data-view="compromisos"]').click();
    const open=rows('COMPROMISOS').find(c=>c.estado==='EN_CURSO');
    let releaseActivity;
    activityGate=new Promise(r=>releaseActivity=r);
    await page.locator(`#commitments-table tr[data-id="${open.compromiso_id}"]`).click();
    assert.ok(await page.locator('#detail-dialog').evaluate(d=>d.open));
    await page.locator('#update-form').waitFor();
    assert.ok((await page.locator('#detail-history').textContent()).includes('cuando lo solicites'));
    await page.locator('#activity-more').click();
    failActivity=true;releaseActivity();activityGate=null;
    await page.waitForFunction(()=>document.querySelector('#activity-more').textContent==='Reintentar actividad');
    assert.ok(await page.locator('#update-form').isVisible());
    await page.locator('#update-form [name="descripcion"]').fill('Unsaved draft');
    await page.evaluate(()=>{window.savedRow=document.querySelector('#commitments-table tr[data-id]');window.savedCell=window.savedRow.firstElementChild;});
    ctx.updateCommitment({compromiso_id:open.compromiso_id,changes:{descripcion:'External edit'}});
    await page.evaluate(()=>document.querySelector('#sync-now').click());
    await page.waitForFunction(()=>document.querySelector('#detail-update-note').textContent.includes('Hay cambios recientes'));
    assert.equal(await page.locator('#update-form [name="descripcion"]').inputValue(),'Unsaved draft');
    assert.ok(await page.evaluate(()=>window.savedRow.isConnected&&window.savedRow.firstElementChild===window.savedCell));
    await page.locator('#update-form button[type="submit"]').click();
    await page.waitForFunction(()=>document.querySelector('#detail-save-error').textContent.length>0);
    assert.equal(await page.locator('#update-form [name="descripcion"]').inputValue(),'Unsaved draft');
    assert.equal(rows('COMPROMISOS').find(c=>c.compromiso_id===open.compromiso_id).descripcion,'External edit');
    await page.locator('[data-action="reload-local-detail"]').click();
    await page.locator('#update-form [name="descripcion"]').fill('Unsaved draft');
    failActivity=false;await page.locator('#activity-more').click();await page.waitForFunction(()=>document.querySelectorAll('#detail-history .list-row').length===40);
    assert.equal(await page.locator('#update-form [name="descripcion"]').inputValue(),'Unsaved draft');
    await page.locator('#activity-more').click();await page.waitForFunction(()=>document.querySelectorAll('#detail-history .list-row').length>40);
    await page.locator('#comment-form textarea').fill('Browser comment');await page.locator('#comment-form button').click();
    await page.waitForFunction(()=>document.querySelector('#detail-content').textContent.includes('Browser comment'));
    assert.equal(await page.locator('#update-form [name="descripcion"]').inputValue(),'Unsaved draft');
    await page.locator('#detail-dialog [data-action="reassign"]').click();await page.locator('#feature-form [name="owner_id"]').selectOption('B');await page.locator('#feature-form [name="aprobador_id"]').selectOption('C');await page.locator('#feature-form [name="motivo"]').fill('Browser reassignment');await page.locator('#feature-save').click();await page.waitForFunction(()=>!document.querySelector('#feature-dialog').open);
    assert.equal(rows('COMPROMISOS').find(c=>c.compromiso_id===open.compromiso_id).owner_id,'B');
    // Closing a pending activity request must never reopen the detail.
    activityGate=new Promise(r=>releaseActivity=r);
    await page.locator(`#commitments-table tr[data-id="${open.compromiso_id}"]`).click();await page.locator('#activity-more').click();await page.locator('#detail-dialog [data-action="close-dialog"]').click();
    releaseActivity();activityGate=null;await page.waitForTimeout(100);assert.equal(await page.locator('#detail-dialog').evaluate(d=>d.open),false);
    await page.locator(`#commitments-table tr[data-id="${open.compromiso_id}"]`).click();await page.locator('#detail-dialog [data-action="cancel-commitment"]').click();await page.locator('#feature-form [name="motivo"]').fill('Browser cancellation');await page.locator('#feature-save').click();await page.waitForFunction(()=>!document.querySelector('#feature-dialog').open);assert.equal(rows('COMPROMISOS').find(c=>c.compromiso_id===open.compromiso_id).estado,'ANULADO');
    // Switching local approvals must preserve the selected decision target.
    const a=ctx.createCommitment({titulo:'Slow approval',tipo_id:'T',owner_id:'B',aprobador_id:'A',fecha_objetivo:'2026-10-10',request_id:uuid(201)});
    const b=ctx.createCommitment({titulo:'Fast approval',tipo_id:'T',owner_id:'B',aprobador_id:'A',fecha_objetivo:'2026-10-10',request_id:uuid(202)});
    const aprA=ctx.submitEvidence({compromiso_id:a.id,url:'https://drive.google.com/a',comentario:'A'}),aprB=ctx.submitEvidence({compromiso_id:b.id,url:'https://drive.google.com/b',comentario:'B'});
    await page.reload();await page.waitForFunction(()=>document.querySelector('#user-name').textContent==='Admin');await page.locator('[data-view="aprobaciones"]').click();
    await page.locator(`#approval-list [data-id="${aprA.approvalId}"]`).click();await page.locator(`#approval-list [data-id="${aprB.approvalId}"]`).click();
    await page.waitForFunction(()=>document.querySelector('#approval-detail').textContent.includes('Fast approval'));
    await new Promise(r=>setTimeout(r,350));assert.ok((await page.locator('#approval-detail').textContent()).includes('Fast approval'));
    await page.locator('#decision-comment').fill('Return B');await page.locator('[data-action="decide"][data-decision="DEVOLVER"]').click();
    await page.waitForFunction(()=>!document.querySelector('#approval-detail [data-action="decide"]'));
    assert.equal(rows('APROBACIONES').find(r=>r.aprobacion_id===aprA.approvalId).estado,'PENDIENTE');assert.equal(rows('APROBACIONES').find(r=>r.aprobacion_id===aprB.approvalId).estado,'DEVUELTO');
    await page.locator('[data-view="admin"]').click();await page.waitForFunction(()=>document.querySelector('#automation-status').textContent.includes('Correos pendientes'));
    await page.screenshot({path:path.join(root,'tests/admin-preview.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});assert.ok(await page.locator('[data-view="admin"]').isVisible());
    assert.equal(rpc.filter(n=>n==='getCommitmentDetail').length,0);
    assert.equal(rpc.filter(n=>n==='getAppData').length,2);
    // Un administrador alterna su vista sin cambiar identidad, rol guardado ni perder borradores.
    assert.ok(await page.locator('#profile-selector-wrap').isVisible());
    failProfile=true;
    await page.locator('#profile-selector').selectOption('RESPONSABLE');
    await page.waitForFunction(()=>document.querySelector('#global-error').textContent.includes('Profile loading failed')&&!document.querySelector('#profile-selector').disabled);
    assert.equal(await page.locator('#profile-selector').inputValue(),'ADMIN');
    assert.ok(await page.locator('[data-view="admin"]').isVisible());
    failProfile=false;
    await page.locator('#profile-selector').selectOption('RESPONSABLE');
    await page.waitForFunction(()=>document.querySelector('#user-role').textContent==='Responsable'&&!document.querySelector('#profile-selector').disabled);
    assert.equal(await page.locator('#user-name').textContent(),'Admin');
    assert.ok(await page.locator('#profile-view-notice').isVisible());
    assert.equal(await page.locator('[data-view="admin"]').isVisible(),false);
    assert.equal(await page.locator(`[data-card="${boardTask.id}"]`).count(),0);
    assert.equal(rows('USUARIOS').find(u=>u.usuario_id==='A').rol_sistema,'ADMIN');
    await page.locator('[data-view="inicio"]').click();await page.locator('#view-inicio [data-action="open-create"]').click();
    await page.locator('#create-form [name="titulo"]').fill('Keep profile draft');
    await page.locator('#profile-selector').evaluate(select=>{select.value='ADMIN';select.dispatchEvent(new Event('change',{bubbles:true}));});
    assert.equal(await page.locator('#profile-selector').inputValue(),'RESPONSABLE');
    assert.equal(await page.locator('#create-form [name="titulo"]').inputValue(),'Keep profile draft');
    await page.locator('#create-dialog [data-action="close-dialog"]').first().click();
    await page.screenshot({path:path.join(root,'tests/profile-view-preview.png'),fullPage:true});
    await page.locator('#profile-selector').selectOption('ADMIN');
    await page.waitForFunction(()=>document.querySelector('#user-role').textContent==='Líder / Administrador'&&!document.querySelector('#profile-selector').disabled);
    assert.ok(await page.locator('[data-view="admin"]').isVisible());
    props.SD_ENV='PRUEBAS';props.SD_SPREADSHEET_ID='mock-browser-test-sheet';setEmail('owner@example.com');
    await page.reload();await page.waitForFunction(()=>document.querySelector('#user-name').textContent==='Owner');
    assert.ok(await page.locator('#environment-badge').isVisible());
    assert.equal(await page.locator('#profile-selector-wrap').isVisible(),false);
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),'Mobile page must not overflow horizontally');
    await page.screenshot({path:path.join(root,'tests/mobile-test-preview.png'),fullPage:true});
    assert.equal(await page.locator('[data-view="admin"]').isVisible(),false);
    const owner=rows('USUARIOS').find(u=>u.usuario_id==='B'),activeColumn=sheets.USUARIOS.rows[0].indexOf('activo');
    sheets.USUARIOS.rows[owner._row-1][activeColumn]=false;
    await page.locator('#sync-now').click();await page.waitForFunction(()=>document.querySelector('#user-name').textContent==='Sin acceso');
    assert.ok((await page.locator('#global-error').textContent()).includes('no está activo'));
    assert.ok(!(await page.locator('#global-error').textContent()).startsWith('AUTH:'));
    sheets.USUARIOS.rows[owner._row-1][activeColumn]=true;delete props.SD_ENV;delete props.SD_SPREADSHEET_ID;setEmail('admin@example.com');
    assert.deepEqual(failures,[]);console.log('PASS: Kanban selector/drag/filter/mobile, checklist persistence and drafts, evidence flow; existing browser regression checks.');
  } finally {if(browser) await browser.close();await new Promise(resolve=>server.close(resolve));}
})().catch(e=>{console.error(e);process.exitCode=1;});
