/** Verifica autorización, migración aditiva y conflictos del checklist sin Sheets reales. */
const assert=require('node:assert/strict');
const {ctx,rows,uuid,sheets,setEmail,io}=require('./server.cjs');
const created=ctx.createCommitment({titulo:'Checklist test',tipo_id:'T',owner_id:'B',aprobador_id:'C',fecha_objetivo:'2026-10-10',request_id:uuid(800)});
let c=created.detail.commitment;
assert.deepEqual(JSON.parse(JSON.stringify(c.checklist)),[]);
const before=io.writes;
setEmail('approver@example.com');
assert.throws(()=>ctx.saveCommitmentChecklist({compromiso_id:created.id,expected_version:c._version,items:[]}),/permisos/);
assert.equal(io.writes,before);
setEmail('owner@example.com');
assert.throws(()=>ctx.saveCommitmentChecklist({compromiso_id:created.id,items:[]}),/versión/);
const step={id:uuid(801),title:'Validar <resultado>',done:false};
const saved=ctx.saveCommitmentChecklist({compromiso_id:created.id,expected_version:c._version,items:[step]});
assert.ok(sheets.COMPROMISOS.rows[0].includes('checklist_json'));
assert.equal(saved.detail.commitment.checklist[0].title,step.title);
assert.equal(saved.detail.commitment.porcentaje_avance,0);
assert.equal(saved.detail.commitment.estado,'PENDIENTE');
assert.throws(()=>ctx.saveCommitmentChecklist({compromiso_id:created.id,expected_version:c._version,items:[]}),/CONFLICT/);
c=saved.detail.commitment;
assert.throws(()=>ctx.saveCommitmentChecklist({compromiso_id:created.id,expected_version:c._version,items:[step,step]}),/duplicado/);
assert.throws(()=>ctx.saveCommitmentChecklist({compromiso_id:created.id,expected_version:c._version,items:[{...step,done:'true'}]}),/inválido/);
const checked=ctx.saveCommitmentChecklist({compromiso_id:created.id,expected_version:c._version,items:[{...step,done:true}]});
assert.equal(checked.detail.commitment.checklist[0].done,true);
assert.equal(rows('HISTORIAL').filter(h=>h.compromiso_id===created.id&&h.accion==='CHECKLIST').length,2);
assert.throws(()=>ctx.updateCommitment({compromiso_id:created.id,changes:{estado:'CERRADO'}}),/Estado no válido/);
ctx.submitEvidence({compromiso_id:created.id,expected_version:checked.detail.commitment._version,url:'https://drive.google.com/test',comentario:'Ready'});
assert.equal(rows('COMPROMISOS').find(r=>r.compromiso_id===created.id).estado,'EN_APROBACION');
assert.throws(()=>ctx.saveCommitmentChecklist({compromiso_id:created.id,expected_version:checked.detail.commitment._version,items:[]}),/antes del envío/);
setEmail('admin@example.com');
console.log('PASS: checklist migration, access, version conflicts, validation, audit and approval boundary.');
