/** Presupuestos de trabajo y tamaño, sin confundir tiempos simulados con latencia de Google. */
const assert=require('node:assert/strict');
const {ctx,rows,uuid,setEmail,cache}=require('./server.cjs');
const large={text:'Á😀'.repeat(45000)};
ctx.optionalCachePut_('TEST-LARGE',large);
assert.equal(ctx.optionalCacheGet_('TEST-LARGE').text,large.text);
const manifest=JSON.parse(cache.get('TEST-LARGE').value);assert.ok(manifest.parts.length>1);
assert.ok(manifest.parts.every(key=>Buffer.byteLength(cache.get(key).value)<100000));
cache.delete(manifest.parts[1]);assert.equal(ctx.optionalCacheGet_('TEST-LARGE'),null,'Un bloque expulsado provoca reconstrucción, nunca datos parciales');
const template=rows('COMPROMISOS').find(c=>c.estado==='EN_CURSO');
ctx.withLock_(()=>ctx.appendRecords_('COMPROMISOS',Array.from({length:250},(_,i)=>({...template,compromiso_id:'PERF-'+i,titulo:'Compromiso de rendimiento '+i,descripcion:'Texto de seguimiento. '.repeat(20),dependencias_json:''}))));
const full=ctx.getAppData(),compact=ctx.getAppData({compact:true});
assert.equal(compact.details.length,full.details.length);
assert.deepEqual(JSON.parse(JSON.stringify(compact.details)),JSON.parse(JSON.stringify(full.details)));
for(const name of ['commitments','myTasks','approvals','users','team','counts'])assert.equal(Object.hasOwn(compact,name),false);
const fullBytes=Buffer.byteLength(JSON.stringify(full)),compactBytes=Buffer.byteLength(JSON.stringify(compact));
assert.ok(compactBytes<fullBytes*0.75,'La respuesta compacta debe eliminar al menos 25% en esta carga conocida');
let builds=0;
const build=ctx.synchronizedDetail_;
ctx.synchronizedDetail_=function(...args){builds++;return build(...args);};
const args=s=>({compact:true,versions:Object.fromEntries(s.details.map(d=>[d.commitment.compromiso_id,d._syncVersion])),metadataVersion:s.metadataVersion,dataVersion:s.dataVersion});
ctx.addCommitmentComment({compromiso_id:'PERF-0',comentario:'Un solo cambio',request_id:uuid(970)});builds=0;
let delta=ctx.syncAppData(args(compact));
assert.equal(delta.details.length,1);assert.equal(builds,1,'Solo construye el detalle afectado, no los 250');assert.equal(delta.metadata,null);
const snapshot=ctx.getAppData({compact:true});builds=0;
delta=ctx.syncAppData({...args(snapshot),force:true});
assert.equal(delta.details.length,0);assert.equal(builds,0,'Actualizar revalida fuentes sin reconstruir detalles iguales');
let dependent=ctx.getAppData({compact:true}).details.find(d=>d.commitment.compromiso_id==='PERF-1');
ctx.saveCommitmentDependencies({compromiso_id:'PERF-1',expected_version:dependent.commitment._version,dependencies:['PERF-0']});
const withDependency=ctx.getAppData({compact:true});
ctx.submitEvidence({compromiso_id:'PERF-0',url:'https://drive.google.com/perf',comentario:'Completo'});builds=0;
delta=ctx.syncAppData(args(withDependency));
assert.deepEqual(Array.from(delta.details,d=>d.commitment.compromiso_id).sort(),['PERF-0','PERF-1']);assert.equal(builds,2);
setEmail('owner@example.com');
const responsible=ctx.getAppData({compact:true});assert.ok(responsible.details.every(d=>d.commitment.owner_id==='B'||d.isTask||d.approvals.some(a=>a.canDecide)));
ctx.synchronizedDetail_=build;
console.log('PASS: respuesta compacta '+compactBytes+'/'+fullBytes+' bytes ('+Math.round((1-compactBytes/fullBytes)*100)+'% menos); sincronización construye 1/'+compact.details.length+' detalles tras un comentario, 0 en refresco idéntico y 2 al cerrar un requisito.');
