/** Línea base protegida y motivos obligatorios contra los servicios Google simulados. */
const assert=require('node:assert/strict');
const {ctx,uuid,rows,io,cache,setEmail}=require('./server.cjs');
const task=ctx.createCommitment({titulo:'Baseline task',tipo_id:'N',owner_id:'B',fecha_objetivo:'2026-11-10',request_id:uuid(960)});
const current=()=>ctx.getAppData().details.find(d=>d.commitment.compromiso_id===task.id);
const update=(changes,reason)=>ctx.updateCommitment({compromiso_id:task.id,expected_version:current().commitment._version,changes,motivo_postergacion:reason});
assert.equal(current().baseline.originalDate,'2026-11-10');assert.equal(current().baseline.source,'CREACION');
assert.equal(current().baseline.delayDays,0);
let before=io.writes,history=rows('HISTORIAL').length;
assert.throws(()=>update({fecha_objetivo:'2026-11-12',estado:'EN_CURSO'}),e=>e.code==='VALIDATION'&&/motivo/.test(e.message));
assert.equal(io.writes,before);assert.equal(rows('HISTORIAL').length,history);assert.equal(current().commitment.estado,'PENDIENTE');
assert.throws(()=>update({fecha_objetivo:'2026-11-12'},'   '),/motivo/);
assert.throws(()=>update({fecha_objetivo:'2026-11-12'},'x'.repeat(2001)),e=>e.code==='VALIDATION');
update({fecha_objetivo:'2026-11-12'},'Esperando al proveedor');
let d=current();assert.equal(d.baseline.originalDate,'2026-11-10');assert.equal(d.baseline.delayDays,2);assert.equal(d.baseline.postponementCount,1);
assert.equal(rows('HISTORIAL').filter(h=>h.compromiso_id===task.id&&h.campo==='fecha_objetivo').at(-1).detalle,'Esperando al proveedor');
update({fecha_objetivo:'2026-11-12'});assert.equal(current().baseline.postponementCount,1);
update({fecha_objetivo:'2026-11-09'});assert.equal(current().baseline.delayDays,0);assert.equal(current().baseline.postponementCount,1);
update({fecha_objetivo:'2026-11-11'},'Replanificación aprobada');assert.equal(current().baseline.delayDays,1);assert.equal(current().baseline.postponementCount,2);
before=io.writes;assert.throws(()=>update({fecha_objetivo_original:'2027-01-01'}),/no editable/);assert.equal(io.writes,before);
cache.clear();assert.equal(current().baseline.postponementCount,2);assert.equal(current().baseline.originalDate,'2026-11-10');
const snapshot=ctx.getAppData();update({fecha_objetivo:'2026-11-14'},'Revisión pendiente');
const delta=ctx.syncAppData({versions:Object.fromEntries(snapshot.details.map(x=>[x.commitment.compromiso_id,x._syncVersion])),metadataVersion:snapshot.metadataVersion,dataVersion:snapshot.dataVersion});
assert.equal(delta.details.find(x=>x.commitment.compromiso_id===task.id).baseline.postponementCount,3);
// Simula registros anteriores a la nueva columna: recupera la primera fecha auditada.
ctx.withLock_(()=>ctx.patchRecord_('COMPROMISOS',current().commitment._row,{fecha_objetivo_original:'',fecha_original_fuente:''}));
assert.equal(current().baseline.originalDate,'2026-11-10');assert.equal(current().baseline.source,'HISTORIAL');
update({fecha_objetivo:'2026-11-13'});assert.equal(current().commitment.fecha_objetivo_original,'2026-11-10');
assert.equal(current().commitment.fecha_original_fuente,'HISTORIAL');
const legacy=ctx.createCommitment({titulo:'Untracked legacy',tipo_id:'N',owner_id:'B',fecha_objetivo:'2026-11-01',request_id:uuid(961)});
let legacyRow=rows('COMPROMISOS').find(c=>c.compromiso_id===legacy.id);
ctx.withLock_(()=>ctx.patchRecord_('COMPROMISOS',legacyRow._row,{fecha_objetivo_original:'',fecha_original_fuente:''}));
let legacyDetail=ctx.getAppData().details.find(x=>x.commitment.compromiso_id===legacy.id);
assert.equal(legacyDetail.baseline.source,'REFERENCIA_ACTUAL');
ctx.updateCommitment({compromiso_id:legacy.id,changes:{fecha_objetivo:'2026-11-05'},motivo_postergacion:'Nueva referencia'});
legacyDetail=ctx.getAppData().details.find(x=>x.commitment.compromiso_id===legacy.id);
assert.equal(legacyDetail.baseline.source,'REFERENCIA_ACTUAL');assert.equal(legacyDetail.baseline.originalDate,'2026-11-01');
const undated=ctx.createCommitment({titulo:'Legacy missing date',tipo_id:'N',owner_id:'B',fecha_objetivo:'2026-11-01',request_id:uuid(962)});
const undatedRow=rows('COMPROMISOS').find(c=>c.compromiso_id===undated.id);
ctx.withLock_(()=>ctx.patchRecord_('COMPROMISOS',undatedRow._row,{fecha_objetivo:'',fecha_objetivo_original:'',fecha_original_fuente:''}));
const assigned=ctx.updateCommitment({compromiso_id:undated.id,changes:{fecha_objetivo:'2026-11-05'}});
assert.equal(assigned.detail.baseline.originalDate,'2026-11-05');assert.equal(assigned.detail.baseline.postponementCount,0);
// Recurrencias también fijan la fecha original y preparar el esquema es idempotente.
assert.ok(rows('COMPROMISOS').filter(c=>c.recurrencia_id).every(c=>c.fecha_original_fuente==='CREACION'&&c.fecha_objetivo_original===c.fecha_objetivo));
before=io.writes;ctx.withLock_(()=>ctx.ensureTrackingSchema_());assert.equal(io.writes,before);
setEmail('approver@example.com');assert.throws(()=>ctx.updateCommitment({compromiso_id:task.id,changes:{fecha_objetivo:'2026-11-20'},motivo_postergacion:'No autorizado'}),e=>e.code==='FORBIDDEN');
setEmail('owner@example.com');ctx.updateCommitment({compromiso_id:task.id,changes:{fecha_objetivo:'2026-11-20'},motivo_postergacion:'Responsable confirma dependencia'});
assert.equal(rows('HISTORIAL').filter(h=>h.compromiso_id===task.id&&h.campo==='fecha_objetivo').at(-1).usuario_id,'B');
setEmail('admin@example.com');
console.log('PASS: immutable baseline, no writes without reason, audited reason, earlier/same dates, repeated postponements, cache/delta, legacy provenance, recurrence, migration and owner permissions.');
